class IssuesGenerator < Rails::Generators::Base
  source_root File.expand_path("templates", __dir__)

  def create_issues
    generate "scaffold", "Issues title:string body:text"
    rails_command "db:migrate"
  end

  def copy_templates
    directory "app", force: true
    directory "test", force: true

    # remove unused files generated by the scaffold
    remove_file "app/views/issues/_form.html.erb"
    remove_file "app/views/issues/_issue.html.erb"
    remove_file "app/views/issues/_issue.json.jbuilder"
    remove_file "app/views/issues/edit.html.erb"
    remove_file "app/views/issues/index.json.jbuilder"
    remove_file "app/views/issues/new.html.erb"
    remove_file "app/views/issues/show.json.jbuilder"

    # remove the default routes and add namespaced routes
    gsub_file "config/routes.rb", 'resources :issues', ''.squish

    inject_into_file "config/routes.rb", after: "  # Additional resources...\n" do <<-EOF
  # Issues
  resources :issues, only: [:index, :show]
  namespace :admin do
    resources :issues
  end
    EOF
    end

    inject_into_file 'config/locales/en.yml', after: "  # Add additional policy messages here...\n" do <<-EOF
    issue_policy:
      index?: "You don't have permission to update issues."
      show?: "You don't have permission to update issues."
      create?: "You don't have permission to update issues."
      new?: "You don't have permission to update issues."
      update?: "You don't have permission to update issues."
      edit?: "You don't have permission to update issues."
      destroy?: "You don't have permission to update issues."
    EOF
    end


    inject_into_file 'config/locales/en.yml', after: "  # Add messages for additional resources here...\n" do <<-EOF
  issues:
      create:
        success: "Your new issue was successfully created."
      delete:
        success: "This issue has been deleted."
      update:
        success: "Your issue was updated."
    EOF
    end

    inject_into_file 'app/views/layouts/shared/admin/_sidebar_menu.html.erb', after: "  <!-- Additional menu items... -->\n" do <<-EOF
    <%= link_to admin_issues_path, class: "group flex items-center px-2 py-2 text-sm leading-5 font-medium text-gray-600 rounded-md hover:text-gray-900 hover:bg-gray-50 focus:outline-none focus:text-gray-900 focus:bg-gray-50 transition ease-in-out duration-150" do %>
      <!-- Heroicon name: clipboard-list -->
      <svg class="mr-3 h-6 w-6
      <% if current_page?(admin_issues_path) %>
        text-gray-500
      <% else %>
        text-gray-400
      <% end %>
      text-gray-400 group-hover:text-gray-500 group-focus:text-gray-500 transition ease-in-out duration-150" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" />
      </svg>
      Issues
    <% end %>
    EOF
    end
  end

  def commit_changes
    # Commit everything to git
    unless ENV["SKIP_GIT"]
      git add: "."
      # git commit will fail if user.email is not configured
      begin
        git commit: %( -m "Adding Issues feature" )
      rescue StandardError => e
        puts e.message
      end
    end
  end

  def confirm_success
    rails_command "test:all"
    say
    say "Your new issues feature is now set up. Tests should still be green if everything was installed correctly.", :green
    say
  end

end
